from selenium import webdriver
from time import sleep

exec_path ="/home/sharmashivansh0000/chromedriver"
yt_link = "https://youtu.be/cuyMD91PE4c"

x0= webdriver.Chrome(executable_path=exec_path)
x1= webdriver.Chrome(executable_path=exec_path)
x2= webdriver.Chrome(executable_path=exec_path)
x3= webdriver.Chrome(executable_path=exec_path)
x4= webdriver.Chrome(executable_path=exec_path)
x5= webdriver.Chrome(executable_path=exec_path)
x6= webdriver.Chrome(executable_path=exec_path)
x7= webdriver.Chrome(executable_path=exec_path)
x8= webdriver.Chrome(executable_path=exec_path)
x9= webdriver.Chrome(executable_path=exec_path)
x10= webdriver.Chrome(executable_path=exec_path)
x11= webdriver.Chrome(executable_path=exec_path)
x12= webdriver.Chrome(executable_path=exec_path)
x13= webdriver.Chrome(executable_path=exec_path)
x14= webdriver.Chrome(executable_path=exec_path)
x15= webdriver.Chrome(executable_path=exec_path)
x16= webdriver.Chrome(executable_path=exec_path)
x17= webdriver.Chrome(executable_path=exec_path)
x18= webdriver.Chrome(executable_path=exec_path)
x19= webdriver.Chrome(executable_path=exec_path)
x20= webdriver.Chrome(executable_path=exec_path)
x21= webdriver.Chrome(executable_path=exec_path)
x22= webdriver.Chrome(executable_path=exec_path)
x23= webdriver.Chrome(executable_path=exec_path)
x24= webdriver.Chrome(executable_path=exec_path)
x25= webdriver.Chrome(executable_path=exec_path)
x26= webdriver.Chrome(executable_path=exec_path)
x27= webdriver.Chrome(executable_path=exec_path)
x28= webdriver.Chrome(executable_path=exec_path)
x29= webdriver.Chrome(executable_path=exec_path)
x30= webdriver.Chrome(executable_path=exec_path)
x31= webdriver.Chrome(executable_path=exec_path)
x32= webdriver.Chrome(executable_path=exec_path)
x33= webdriver.Chrome(executable_path=exec_path)
x34= webdriver.Chrome(executable_path=exec_path)
x35= webdriver.Chrome(executable_path=exec_path)
x36= webdriver.Chrome(executable_path=exec_path)
x37= webdriver.Chrome(executable_path=exec_path)
x38= webdriver.Chrome(executable_path=exec_path)
x39= webdriver.Chrome(executable_path=exec_path)
x40= webdriver.Chrome(executable_path=exec_path)
x41= webdriver.Chrome(executable_path=exec_path)
x42= webdriver.Chrome(executable_path=exec_path)
x43= webdriver.Chrome(executable_path=exec_path)
x44= webdriver.Chrome(executable_path=exec_path)
x45= webdriver.Chrome(executable_path=exec_path)
x46= webdriver.Chrome(executable_path=exec_path)
x47= webdriver.Chrome(executable_path=exec_path)
x48= webdriver.Chrome(executable_path=exec_path)
x49= webdriver.Chrome(executable_path=exec_path)
x50= webdriver.Chrome(executable_path=exec_path)
x51= webdriver.Chrome(executable_path=exec_path)
x52= webdriver.Chrome(executable_path=exec_path)
x53= webdriver.Chrome(executable_path=exec_path)
x54= webdriver.Chrome(executable_path=exec_path)
x55= webdriver.Chrome(executable_path=exec_path)
x56= webdriver.Chrome(executable_path=exec_path)
x57= webdriver.Chrome(executable_path=exec_path)
x58= webdriver.Chrome(executable_path=exec_path)
x59= webdriver.Chrome(executable_path=exec_path)
x60= webdriver.Chrome(executable_path=exec_path)
x61= webdriver.Chrome(executable_path=exec_path)
x62= webdriver.Chrome(executable_path=exec_path)
x63= webdriver.Chrome(executable_path=exec_path)
x64= webdriver.Chrome(executable_path=exec_path)
x65= webdriver.Chrome(executable_path=exec_path)
x66= webdriver.Chrome(executable_path=exec_path)
x67= webdriver.Chrome(executable_path=exec_path)
x68= webdriver.Chrome(executable_path=exec_path)
x69= webdriver.Chrome(executable_path=exec_path)
x70= webdriver.Chrome(executable_path=exec_path)
x71= webdriver.Chrome(executable_path=exec_path)
x72= webdriver.Chrome(executable_path=exec_path)
x73= webdriver.Chrome(executable_path=exec_path)
x74= webdriver.Chrome(executable_path=exec_path)
x75= webdriver.Chrome(executable_path=exec_path)
x76= webdriver.Chrome(executable_path=exec_path)
x77= webdriver.Chrome(executable_path=exec_path)
x78= webdriver.Chrome(executable_path=exec_path)
x79= webdriver.Chrome(executable_path=exec_path)
x80= webdriver.Chrome(executable_path=exec_path)
x81= webdriver.Chrome(executable_path=exec_path)
x82= webdriver.Chrome(executable_path=exec_path)
x83= webdriver.Chrome(executable_path=exec_path)
x84= webdriver.Chrome(executable_path=exec_path)
x85= webdriver.Chrome(executable_path=exec_path)
x86= webdriver.Chrome(executable_path=exec_path)
x87= webdriver.Chrome(executable_path=exec_path)
x88= webdriver.Chrome(executable_path=exec_path)
x89= webdriver.Chrome(executable_path=exec_path)
x90= webdriver.Chrome(executable_path=exec_path)
x91= webdriver.Chrome(executable_path=exec_path)
x92= webdriver.Chrome(executable_path=exec_path)
x93= webdriver.Chrome(executable_path=exec_path)
x94= webdriver.Chrome(executable_path=exec_path)
x95= webdriver.Chrome(executable_path=exec_path)
x96= webdriver.Chrome(executable_path=exec_path)
x97= webdriver.Chrome(executable_path=exec_path)
x98= webdriver.Chrome(executable_path=exec_path)
x99= webdriver.Chrome(executable_path=exec_path)


x0.get(yt_link)
x1.get(yt_link)
x2.get(yt_link)
x3.get(yt_link)
x4.get(yt_link)
x5.get(yt_link)
x6.get(yt_link)
x7.get(yt_link)
x8.get(yt_link)
x9.get(yt_link)
x10.get(yt_link)
x11.get(yt_link)
x12.get(yt_link)
x13.get(yt_link)
x14.get(yt_link)
x15.get(yt_link)
x16.get(yt_link)
x17.get(yt_link)
x18.get(yt_link)
x19.get(yt_link)
x20.get(yt_link)
x21.get(yt_link)
x22.get(yt_link)
x23.get(yt_link)
x24.get(yt_link)
x25.get(yt_link)
x26.get(yt_link)
x27.get(yt_link)
x28.get(yt_link)
x29.get(yt_link)
x30.get(yt_link)
x31.get(yt_link)
x32.get(yt_link)
x33.get(yt_link)
x34.get(yt_link)
x35.get(yt_link)
x36.get(yt_link)
x37.get(yt_link)
x38.get(yt_link)
x39.get(yt_link)
x40.get(yt_link)
x41.get(yt_link)
x42.get(yt_link)
x43.get(yt_link)
x44.get(yt_link)
x45.get(yt_link)
x46.get(yt_link)
x47.get(yt_link)
x48.get(yt_link)
x49.get(yt_link)
x50.get(yt_link)
x51.get(yt_link)
x52.get(yt_link)
x53.get(yt_link)
x54.get(yt_link)
x55.get(yt_link)
x56.get(yt_link)
x57.get(yt_link)
x58.get(yt_link)
x59.get(yt_link)
x60.get(yt_link)
x61.get(yt_link)
x62.get(yt_link)
x63.get(yt_link)
x64.get(yt_link)
x65.get(yt_link)
x66.get(yt_link)
x67.get(yt_link)
x68.get(yt_link)
x69.get(yt_link)
x70.get(yt_link)
x71.get(yt_link)
x72.get(yt_link)
x73.get(yt_link)
x74.get(yt_link)
x75.get(yt_link)
x76.get(yt_link)
x77.get(yt_link)
x78.get(yt_link)
x79.get(yt_link)
x80.get(yt_link)
x81.get(yt_link)
x82.get(yt_link)
x83.get(yt_link)
x84.get(yt_link)
x85.get(yt_link)
x86.get(yt_link)
x87.get(yt_link)
x88.get(yt_link)
x89.get(yt_link)
x90.get(yt_link)
x91.get(yt_link)
x92.get(yt_link)
x93.get(yt_link)
x94.get(yt_link)
x95.get(yt_link)
x96.get(yt_link)
x97.get(yt_link)
x98.get(yt_link)
x99.get(yt_link)


while True:
    sleep(18)
    x0.refresh()
    x1.refresh()
    x2.refresh()
    x3.refresh()
    x4.refresh()
    x5.refresh()
    x6.refresh()
    x7.refresh()
    x8.refresh()
    x9.refresh()
    x10.refresh()
    x11.refresh()
    x12.refresh()
    x13.refresh()
    x14.refresh()
    x15.refresh()
    x16.refresh()
    x17.refresh()
    x18.refresh()
    x19.refresh()
    x20.refresh()
    x21.refresh()
    x22.refresh()
    x23.refresh()
    x24.refresh()
    x25.refresh()
    x26.refresh()
    x27.refresh()
    x28.refresh()
    x29.refresh()
    x30.refresh()
    x31.refresh()
    x32.refresh()
    x33.refresh()
    x34.refresh()
    x35.refresh()
    x36.refresh()
    x37.refresh()
    x38.refresh()
    x39.refresh()
    x40.refresh()
    x41.refresh()
    x42.refresh()
    x43.refresh()
    x44.refresh()
    x45.refresh()
    x46.refresh()
    x47.refresh()
    x48.refresh()
    x49.refresh()
    x50.refresh()
    x51.refresh()
    x52.refresh()
    x53.refresh()
    x54.refresh()
    x55.refresh()
    x56.refresh()
    x57.refresh()
    x58.refresh()
    x59.refresh()
    x60.refresh()
    x61.refresh()
    x62.refresh()
    x63.refresh()
    x64.refresh()
    x65.refresh()
    x66.refresh()
    x67.refresh()
    x68.refresh()
    x69.refresh()
    x70.refresh()
    x71.refresh()
    x72.refresh()
    x73.refresh()
    x74.refresh()
    x75.refresh()
    x76.refresh()
    x77.refresh()
    x78.refresh()
    x79.refresh()
    x80.refresh()
    x81.refresh()
    x82.refresh()
    x83.refresh()
    x84.refresh()
    x85.refresh()
    x86.refresh()
    x87.refresh()
    x88.refresh()
    x89.refresh()
    x90.refresh()
    x91.refresh()
    x92.refresh()
    x93.refresh()
    x94.refresh()
    x95.refresh()
    x96.refresh()
    x97.refresh()
    x98.refresh()
    x99.refresh()
    
    
