from selenium import webdriver
from time import sleep

exec_path ="path_to_exe"
yt_link = "yt_link"

x0= webdriver.Chrome(executable_path=exec_path)
x1= webdriver.Chrome(executable_path=exec_path)
x2= webdriver.Chrome(executable_path=exec_path)
x3= webdriver.Chrome(executable_path=exec_path)
x4= webdriver.Chrome(executable_path=exec_path)
x5= webdriver.Chrome(executable_path=exec_path)
x6= webdriver.Chrome(executable_path=exec_path)
x7= webdriver.Chrome(executable_path=exec_path)
x8= webdriver.Chrome(executable_path=exec_path)
x9= webdriver.Chrome(executable_path=exec_path)
x10= webdriver.Chrome(executable_path=exec_path)
x11= webdriver.Chrome(executable_path=exec_path)
x12= webdriver.Chrome(executable_path=exec_path)
x13= webdriver.Chrome(executable_path=exec_path)
x14= webdriver.Chrome(executable_path=exec_path)
x15= webdriver.Chrome(executable_path=exec_path)
x16= webdriver.Chrome(executable_path=exec_path)
x17= webdriver.Chrome(executable_path=exec_path)
x18= webdriver.Chrome(executable_path=exec_path)
x19= webdriver.Chrome(executable_path=exec_path)
x20= webdriver.Chrome(executable_path=exec_path)
x21= webdriver.Chrome(executable_path=exec_path)
x22= webdriver.Chrome(executable_path=exec_path)
x23= webdriver.Chrome(executable_path=exec_path)
x24= webdriver.Chrome(executable_path=exec_path)
x25= webdriver.Chrome(executable_path=exec_path)
x26= webdriver.Chrome(executable_path=exec_path)
x27= webdriver.Chrome(executable_path=exec_path)
x28= webdriver.Chrome(executable_path=exec_path)
x29= webdriver.Chrome(executable_path=exec_path)
x30= webdriver.Chrome(executable_path=exec_path)

x0.get(yt_link)
x1.get(yt_link)
x2.get(yt_link)
x3.get(yt_link)
x4.get(yt_link)
x5.get(yt_link)
x6.get(yt_link)
x7.get(yt_link)
x8.get(yt_link)
x9.get(yt_link)
x10.get(yt_link)
x11.get(yt_link)
x12.get(yt_link)
x13.get(yt_link)
x14.get(yt_link)
x15.get(yt_link)
x16.get(yt_link)
x17.get(yt_link)
x18.get(yt_link)
x19.get(yt_link)
x20.get(yt_link)
x21.get(yt_link)
x22.get(yt_link)
x23.get(yt_link)
x24.get(yt_link)
x25.get(yt_link)
x26.get(yt_link)
x27.get(yt_link)
x28.get(yt_link)
x29.get(yt_link)
x30.get(yt_link)

while True:
    sleep(18)
    x0.refresh()
    x1.refresh()
    x2.refresh()
    x3.refresh()
    x4.refresh()
    x5.refresh()
    x6.refresh()
    x7.refresh()
    x8.refresh()
    x9.refresh()
    x10.refresh()
    x11.refresh()
    x12.refresh()
    x13.refresh()
    x14.refresh()
    x15.refresh()
    x16.refresh()
    x17.refresh()
    x18.refresh()
    x19.refresh()
    x20.refresh()
    x21.refresh()
    x22.refresh()
    x23.refresh()
    x24.refresh()
    x25.refresh()
    x26.refresh()
    x27.refresh()
    x28.refresh()
    x29.refresh()
    x30.refresh()
